name: Unity Build

on:
  pull_request: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - wave
        unityVersion:
          - 2019.4.11f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
        targetItchio:
          - osx
          - windows
          - linux
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      # Build
      - name: Unity - Builder
        uses: game-ci/unity-builder@v1.5
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ${{ matrix.projectPath }}_${{ matrix.targetPlatform }}
          
      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.projectPath }}_${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      
      # Upload windows release
      - name: Release ${{ matrix.targetPlatform }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.targetItchio }}
          ITCH_GAME: wave
          ITCH_USER: HawkTheHuman
          PACKAGE: build/${{ matrix.targetPlatform }}/${{ matrix.projectPath }}_${{ matrix.targetPlatform }}.zip
