name: Unity-Build

# Run this workflow every time a new commit pushed to your repository except for main branch, who runs it on pull request
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
  
jobs:
  build-all-supported-platforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.11f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Build
      - name: Unity Builder
        uses: game-ci/unity-builder@v1.5
        with:
          projectPath: ${{ env.PROJECT_PATH }} }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ${{ env.PROJECT_PATH }}_${{ matrix.targetPlatform }}
          
      # Output
      - name: Output ${{ matrix.targetPlatform }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_PATH }}_${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
