name: Upload Release to Itchio
on:
  push: { branches: [main] }
    # Sequence of patterns matched against refs/tags
    #tags:
    #- 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  windowsRelease:
    name: Upload Windows Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - wave
        unityVersion:
          - 2019.4.11f1
        targetPlatform:
          - StandaloneWindows # Build a Windows standalone.
        targetItchio:
          - windows
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Build
      - name: Unity Builder
        uses: game-ci/unity-builder@v1.5
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ${{ matrix.projectPath }}_${{ matrix.targetPlatform }}
          
      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.projectPath }}_${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          
      - name: Download Window Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.projectPath }}_${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          
      # Upload windows release
      - name: Release ${{ matrix.targetPlatform }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.targetItchio }}
          ITCH_GAME: wave
          ITCH_USER: HawkTheHuman
          PACKAGE: build/${{ matrix.targetPlatform }}/${{ matrix.projectPath }}_${{ matrix.targetPlatform }}.zip
