name: Release-Itch.io

# Run this workflow every time a new commit is pushed to main
on:
  push:
    branches: [main]
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
  
jobs:
  unity-build:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.11f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Build
      - name: Unity Builder
        uses: game-ci/unity-builder@v1.5
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ${{ env.PROJECT_PATH }}_${{ matrix.targetPlatform }}
          
      # Output
      - name: Output ${{ matrix.targetPlatform }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_PATH }}_${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  release-windows-itchio:
    name: Upload Windows release to Itch.io
    runs-on: ubuntu-latest
    needs: unity-build
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.11f1
        targetPlatform:
          - StandaloneWindows # Build a Windows standalone.
        targetItchio:
          - windows
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Get artifact
      - name: Download StandaloneWindows build artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.PROJECT_PATH }}_${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          
      # Upload release
      - name: Release StandaloneWindows
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.targetItchio }}
          ITCH_GAME: wave
          ITCH_USER: HawkTheHuman
          PACKAGE: build/${{ matrix.targetPlatform }}
          
  release-osx-itchio:
    name: Upload OSX release to Itch.io
    runs-on: ubuntu-latest
    needs: unity-build
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.11f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
        targetItchio:
          - osx
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Get artifact
      - name: Download StandaloneOSX build artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.PROJECT_PATH }}_${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          
      # Upload release
      - name: Release StandaloneOSX
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.targetItchio }}
          ITCH_GAME: wave
          ITCH_USER: HawkTheHuman
          PACKAGE: build/${{ matrix.targetPlatform }}
          
  release-linux-itchio:
    name: Upload Linux release to Itch.io
    runs-on: ubuntu-latest
    needs: unity-build
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.11f1
        targetPlatform:
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
        targetItchio:
          - linux
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Get artifact
      - name: Download StandaloneLinux64 build artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.PROJECT_PATH }}_${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          
      # Upload release
      - name: Release StandaloneLinux64
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.targetItchio }}
          ITCH_GAME: wave
          ITCH_USER: HawkTheHuman
          PACKAGE: build/${{ matrix.targetPlatform }}
