name: Unity-Tests

# Run this workflow every time a new commit pushed to your repository except for main branch, who runs it on pull request
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
jobs:
  test-all-modes:
    name: Test all Unity modes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.11f1
        testMode:
          - playmode
          - editmode
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Test
      - name: Run ${{ matrix.testMode }} tests
        uses: game-ci/unity-test-runner@v1.3
        id: tests
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts

      # Output
      - name: Upload ${{ matrix.testMode }} test results
        uses: actions/upload-artifact@v1
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
